### ISSUE TITLE
Enable [Join a Team] even if user is already part of a Team

### ISSUE THREAD

**Issue by fjgallard** [nbcp/leaderboard#117] opened 2019-08-19 07:17 UTC
Temporarily labeled as "suggestions".

Might have to enable Join a Team even if the user already has a Team; some tasks are simply too tedious for admin work and this would alleviate certain tasks.

Allow [Join a Team] action even if user has an approved Membership already.

**Comment by nbcp** [comment] 2020-09-29 08:39
This is already a duplicate of #199

**Closed by nbcp** 2020-09-29 08:39 UTC
Labels: suggestions
